---
baseyaml: |
  sidebar-section:
    - title: Blog
      links:
        - href: /blog/devlog
          target: null
          label: Devlogs
          nested: null
        - href: /blog/thoughts
          target: null
          label: Thoughts
          nested: null
    - title: My Bookmarks
      links:
        - href: //sadgrl.online
          target: _blank
          label: sadgrl.online
          nested: null
        - href: //maia.crimew.gay
          target: _blank
          label: maia.crimew.gay
          nested: null
        - href: //cinni.net
          target: _blank
          label: cinni.net
          nested: null
        - href: //neocities.org
          target: _blank
          label: neocities.org
          nested: null
        - href: //yesterweb.org
          target: _blank
          label: yesterweb.org
          nested: null
  sidebar-content-down: null
  navbar:
    - href: /
      label: Home
    - href: /blog
      label: Blog
  header-html: |
    <img src="/files/images/base/logo.png" alt="" style="margin-left: 20px; margin-top: auto; margin-bottom: auto; height: 100px; image-rendering: pixelated;">
  footer: >
    <a rel="license"
    href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative
    Commons License" style="border-width:0"
    src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a> <a rel="license"
    href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons
    Attribution-ShareAlike 4.0 International License</a>
  buttons:
    - href: //anybrowser.org
      imgsrc: /files/88x31/anybrowser3.gif
      width: 88
      height: 31
    - href: //www.mozilla.org/en-US/firefox/new/
      imgsrc: /files/88x31/firefox.gif
      width: 88
      height: 31
    - href: //fediverse.party/
      imgsrc: /files/88x31/join-fediverse.gif
      width: 88
      height: 31
    - href: //yesterweb.org/no-to-web3/
      imgsrc: /files/88x31/noweb3.gif
      width: 88
      height: 31
    - href: //debian.org
      imgsrc: /files/88x31/debian.gif
      width: 88
      height: 31
    - imgsrc: /files/88x31/hatemac_b.gif
      width: 88
      height: 31
    - imgsrc: /files/88x31/hatems.gif
      width: 88
      height: 31
    - imgsrc: /files/88x31/ipv6.gif
      width: 88
      height: 31
    - imgsrc: /files/88x31/jobsritchie.gif
      width: 88
      height: 31
    - imgsrc: /files/88x31/linux-p.gif
      width: 88
      height: 31
    - href: //mastodon.social
      imgsrc: /files/88x31/masto.gif
      width: 88
      height: 31
    - href: //mozilla.org
      imgsrc: /files/88x31/mozilla2.gif
      width: 88
      height: 31
    - imgsrc: /files/88x31/neovim.gif
      width: 88
      height: 31
    - imgsrc: /files/88x31/piracy.gif
      width: 88
      height: 31
    - href: //sadgrl.online
      imgsrc: /files/88x31/sadgrlonline.gif
      width: 88
      height: 31
    - href: //github.com/Aesistril/aesistril-website
      imgsrc: /files/88x31/this-website-is-open-source.webp
      width: 88
      height: 31

  buttons_container_html: |
    <iframe src="//incr.easrng.net/badge?key=aesistrilswebsite" style="background: url(//incr.easrng.net/bg.gif);" title="increment badge" width="88" height="31" frameborder="0"></iframe>
---
